apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- ../../crd
- ../../rbac
- ../../package
images:
- name: ghcr.io/weaveworks/tf-controller
  newName: weaveworks/tf-controller
