name: Release runners

on:
  repository_dispatch:
    types: [release-runners]

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

env:
  CONTROLLER: ${{ github.event.client_payload.controller }}
  VERSION: ${{ github.event.client_payload.version }}
  BUILD_DATE: ${{ github.event.client_payload.build_date }}

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version: [1.0.11, 1.1.9, 1.2.9, 1.3.9, 1.4.6]
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: "--debug"
      - name: Login to Docker Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish multi-arch tf-runner container images
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./runner.Dockerfile
          platforms: linux/amd64,linux/arm64 #,linux/arm/v7
          tags: |
            ghcr.io/weaveworks/tf-runner:${{ env.VERSION }}-tf-${{ matrix.tf_version }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.created=${{ env.BUILD_DATE }}
